# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('venue', models.CharField(max_length=200)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('facebook', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('profile_pic', models.ImageField(upload_to='speakers')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=30)),
                ('type', models.CharField(choices=[('df', 'Default'), ('br', 'Break')], max_length=7)),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('about', models.TextField()),
                ('facebook', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='speakers')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='talks.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='talks.Event')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='talks.Speaker'),
        ),
    ]
