# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20170925_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='talks.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='talks.Event'),
            preserve_default=False,
        ),
    ]
