# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20170925_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
