# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20170925_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='MAC AUDITORIUM', max_length=200),
            preserve_default=False,
        ),
    ]
