# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
