# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_event_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=30)),
                ('type', models.CharField(choices=[('df', 'Default'), ('br', 'Break')], max_length=7)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk', to='talks.Speaker')),
            ],
        ),
    ]
