# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
