# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_auto_20171008_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(),
        ),
    ]
